version: 2.1
general:
  branches:
    only:
      - master
      - develop
      - circleci-project-setup
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
      - store_test_results:
          path: test-results/jest
  deploy-production-ssh:
    docker:
      - image: kroniak/ssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b4:13:f8:86:b6:d3:3b:ab:bd:fd:51:f0:b4:3f:a7:b9"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $HOST_USER@$HOST_NAME -p $HOST_PORT "$DEPLOY_CMD"

workflows:
  build-and-test-deploy:
    jobs:
      - build-and-test
      - deploy-production-ssh:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
