version: 2.1
general:
  branches:
    only:
      - master
      - develop
      - circleci-project-setup
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
      - store_test_results:
          path: test-results/jest
workflows:
  build-and-test:
    jobs:
      - build-and-test
