version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
      - store_test_results:
          path: test-results/jest
  deploy-production-ssh:
    docker:
      - image: kroniak/ssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_PUBLIC_KEY
      - run:
          name: Deploy Over SSH
          command: |
            yarn build
            tar -caf build.tar.gz  *
            scp -P $HOST_PORT -o "StrictHostKeyChecking no" build.tar.gz $HOST_USER@$HOST_NAME:~/build/
            rm -f build.tar.gz
            ssh $HOST_USER@$HOST_NAME -p $HOST_PORT -o "StrictHostKeyChecking no" "$DEPLOY_CMD"

workflows:
  build-and-test-deploy:
    jobs:
      - build-and-test
      - deploy-production-ssh:
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
