version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:

  # Simple test app
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
      - store_test_results:
          path: test-results/jest

  # Build app into single archive
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run:
          name: Build Artefact for Production
          command: |
            yarn build
            tar -caf build.tar.gz  *
      - persist_to_workspace:
          root: ./
          paths:
            - build.tar.gz

  # Deploy over SSH and run deploy script
  deploy-production-ssh:
    docker:
      - image: kroniak/ssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_PUBLIC_KEY
      - attach_workspace:
          at: ./
      - run:
          name: Deploy Over SSH
          command: |
            scp -P $HOST_PORT -o "StrictHostKeyChecking no" build.tar.gz $HOST_USER@$HOST_NAME:~/build/
            ssh $HOST_USER@$HOST_NAME -p $HOST_PORT -o "StrictHostKeyChecking no" "$DEPLOY_CMD"

workflows:
  build-and-test-deploy:
    jobs:
      - test
      - build-production:
          filters:
            branches:
              only:
                - master
            requires:
              - test
      - deploy-production-ssh:
          filters:
            branches:
              only:
                - master
          requires:
            - build-production
